<a href="https://colab.research.google.com/github/THEnormalguYYy/stackomatic-assignments/blob/main/stackomaticassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PART 1: DATA EXPLORATION WITH PANDAS

In [5]:
import numpy as np
import pandas as pd

df=pd.read_csv('california_housing_train.csv')



In [6]:
display(df.head(5),df.tail(10))

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [7]:
df.describe()# Stasticial summary of data

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [9]:
uniquebedrooms = df['total_bedrooms'].unique()#filter distinct numbers in total_bedrooms
no_uniquebedrooms = len(uniquebedrooms)#number of elements in uniquebedrooms

display(uniquebedrooms)
no_uniquebedrooms

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

1848

In [10]:
newdf=df
newdf['total_bedrooms_per_total_rooms']=newdf['total_bedrooms']/newdf['total_rooms']#create new column
print(newdf['total_bedrooms_per_total_rooms'].mean())
print(newdf['total_bedrooms_per_total_rooms'].std())


0.21275998821034803
0.057823008903161756


In [11]:
newdf[newdf['median_income']>5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [12]:
newdf2=newdf[(newdf['total_rooms']>10000) & (newdf['median_house_value']<150000)]
display(newdf2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [13]:
newdf.to_csv('newdata.csv')#saving

**PART 2: NUMERICAL ANALYSIS WITH NUMPY**

ARRAY CREATION AND INDEXING

In [ ]:
import numpy as np

a = np.array([])
for i in range(1,21):
  a = np.append(a,i)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [ ]:
print(a[1:20:2])

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [ ]:
b = np.random.randint(10,100, size = (5,4))
print(b)

[[64 44 12 83]
 [85 34 32 61]
 [15 36 59 44]
 [63 73 58 15]
 [87 71 42 70]]


In [ ]:
print(b[0:3,0:2])

[[64 44]
 [85 34]
 [15 36]]


ARRAY MANUPULATION

In [ ]:
x = a.reshape((4,5))
print(x)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [ ]:
y = x.reshape((1,20))
print(y)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]


In [ ]:
z = np.random.random(size=(5,3))
print(z)
np.matmul(x,z)

[[0.04241035 0.23539601 0.49612012]
 [0.51417424 0.65686705 0.81075567]
 [0.83791699 0.47769009 0.04423685]
 [0.43484585 0.94271382 0.29252721]
 [0.02430865 0.52207919 0.81593572]]


array([[ 5.44543647,  9.36345163,  7.50012951],
       [14.71371692, 23.53718249, 19.79800745],
       [23.98199737, 37.71091335, 32.09588539],
       [33.25027783, 51.88464421, 44.39376333]])

BOOLEAN AND FANCY INDEXING

In [ ]:
a = np.random.randint(100, size = (50))
print(a)

[43 12 84 14 90  7 55 85  7 63 12 62 70 88 89 80 26 96 41 53 66 61 20 72
 34 34 42 67  9 77 56 49 14 98 53 93 94 58 31 82 20 97 84 51 53 78 31 96
 11  7]


array([84, 90, 55, 85, 63, 62, 70, 88, 89, 80, 96, 53, 66, 61, 72, 67, 77,
       56, 98, 53, 93, 94, 58, 82, 97, 84, 51, 53, 78, 96])

In [ ]:
a[a>50]

array([84, 90, 55, 85, 63, 62, 70, 88, 89, 80, 96, 53, 66, 61, 72, 67, 77,
       56, 98, 53, 93, 94, 58, 82, 97, 84, 51, 53, 78, 96])

In [ ]:
i = int(input("element index: "))
print(a[i])


element index: 5
7


STATISTICAL **OPERATIONS**

In [ ]:
print(b)
print(np.mean(b, axis = 0))#mean along each column
print(np.sum(b, axis = 0))#sum along each column
print(np.max(b, axis = 0))#max along each column


[[64 44 12 83]
 [85 34 32 61]
 [15 36 59 44]
 [63 73 58 15]
 [87 71 42 70]]
[62.8 51.6 40.6 54.6]
[314 258 203 273]
[87 73 59 83]


BASIC PYTHON: PART3

In [ ]:
a1 = 1
a2 = 1
while a1 <= 100:
  print(a1)
  a = a1 + a2
  a1 = a2
  a2 = a

1
1
2
3
5
8
13
21
34
55
89


In [ ]:
for i in range(1,51):
  if i % 3 == 0 and i % 5 == 0:
    print(str(i) + ".FizzBuzz")
  elif i % 3 == 0:
    print(str(i) + ".Fizz")
  elif i % 5 == 0:
    print(str(i) + ".Buzz")
  else:
    print(str(i) + ".")

1.
2.
3.Fizz
4.
5.Buzz
6.Fizz
7.
8.
9.Fizz
10.Buzz
11.
12.Fizz
13.
14.
15.FizzBuzz
16.
17.
18.Fizz
19.
20.Buzz
21.Fizz
22.
23.
24.Fizz
25.Buzz
26.
27.Fizz
28.
29.
30.FizzBuzz
31.
32.
33.Fizz
34.
35.Buzz
36.Fizz
37.
38.
39.Fizz
40.Buzz
41.
42.Fizz
43.
44.
45.FizzBuzz
46.
47.
48.Fizz
49.
50.Buzz


In [ ]:
num = int(input("how many numbers are you entering?: "))
a = 1
b = []
for i in range(num):
  x = float(input("enter a number: "))
  b.append(x)

b.sort()

if num % 2 == 0:
  print((b[int(num/2 - 1)] + b[int(num/2)])/2)
else:
  print(b[int((num - 1)/2)])

how many numbers are you entering?: 3
enter a number: 1
enter a number: 2
enter a number: 3
2.0


In [ ]:

  num = float(input("how many numbers are you entering?: "))
  a = 1
  x = 0
  while a <= num:
    x += float(input("enter a number: "))
    a += 1
try:
    print("Average of the given numbers: " + str(x/num))
except ZeroDivisionError:
    print("invalid input")





how many numbers are you entering?: 0
invalid input


In [ ]:
try:
  a = float(input("enter ur 1st number: "))
  b = float(input("enter ur 2nd number: "))
  print("a/b =" + str(a/b))
except ZeroDivisionError:
  print("invalid input")

enter ur 1st number: 1
enter ur 2nd number: 0
invalid input


PART 4: BONUS CHALLENGE


In [ ]:
p = np.random.rand(3,4,5)*10
print(p)

[[[6.07371555 8.73155925 5.76289106 1.62624326 8.68408445]
  [8.66907416 7.30626394 1.19914    1.86604429 6.20572439]
  [0.94353704 0.73438391 5.89737454 7.03951441 0.07937977]
  [5.41655603 1.83463516 0.81578512 2.25757696 7.51469076]]

 [[0.27717348 4.19652136 3.25001624 9.54524924 8.05914445]
  [5.06938853 3.25949765 6.34849002 3.53661422 9.95331804]
  [7.27614347 4.03267466 9.47339081 8.96449828 1.15384274]
  [0.12154747 6.95158166 5.68289138 0.72995131 9.20160937]]

 [[8.39173441 5.11591259 8.79710756 0.93445766 1.44174677]
  [9.86468373 3.90115501 3.01770902 2.02129164 9.96974486]
  [2.94105873 7.17348632 0.92421463 1.24286232 4.52265062]
  [7.67866743 1.76170026 8.52951501 6.52237201 4.81654122]]]
